import type { Href } from 'expo-router';

/**
 * Cast a string path to an Expo Router `Href`.
 *
 * Typed-routes are regenerated by the Expo CLI (dev server / export), so during a
 * plain `tsc` run new group routes may not exist in the generated union yet. This
 * helper keeps navigation type-safe at the call boundary without depending on that
 * regeneration order.
 */
export const asHref = (path: string): Href => path as Href;

/** Centralized app route hrefs (groups qualified so the auth guard is deterministic). */
export const routes = {
  auth: asHref('/(auth)'),
  /** Email OTP confirmation after create account. */
  confirmEmail: (email: string): Href =>
    asHref(`/(auth)/confirm-email?email=${encodeURIComponent(email)}`),
  tabs: asHref('/(tabs)'),
  /** Browse tab — search affordance + genre chips + category grid. */
  browse: asHref('/(tabs)/browse'),
  /** Saved tab — placeholder shell (no persistence yet). */
  saved: asHref('/(tabs)/saved'),
  /** Profile tab. */
  profile: asHref('/(tabs)/profile'),
  /**
   * Search — root Stack screen above `(tabs)`, so Back returns to the tab that
   * pushed it (e.g. Browse) instead of resetting to the tabs' initial route.
   */
  search: asHref('/search'),
  /**
   * Title detail — root Stack screen above `(tabs)`, so Back returns to the
   * tab that pushed it (e.g. Decider Results) instead of resetting to Home.
   */
  title: (id: string): Href => asHref(`/title/${id}`),
  /**
   * Category story viewer — root Stack screen above `(tabs)` (mirrors `title`),
   * so Back returns to the Search tab that pushed it instead of resetting tabs.
   */
  story: (category: string): Href => asHref(`/story/${category}`),
  /** Friends management (hidden tab), from Profile. */
  friends: asHref('/(tabs)/friends'),
  /** Deep-link invite accept route (outside tab bar). */
  inviteAccept: (code: string): Href => asHref(`/invite/${code}`),
  onboarding: {
    services: asHref('/(onboarding)/services'),
    tasteSeed: asHref('/(onboarding)/taste-seed'),
    handle: asHref('/(onboarding)/handle'),
    watchWith: asHref('/(onboarding)/watch-with'),
    invite: asHref('/(onboarding)/invite'),
    notifications: asHref('/(onboarding)/notifications'),
  },
} as const;
