import type { Href } from 'expo-router';

/**
 * Cast a string path to an Expo Router `Href`.
 *
 * Typed-routes are regenerated by the Expo CLI (dev server / export), so during a
 * plain `tsc` run new group routes may not exist in the generated union yet. This
 * helper keeps navigation type-safe at the call boundary without depending on that
 * regeneration order.
 */
export const asHref = (path: string): Href => path as Href;

/** Centralized app route hrefs (groups qualified so the auth guard is deterministic). */
export const routes = {
  auth: asHref('/(auth)'),
  /** Email OTP confirmation after create account. */
  confirmEmail: (email: string): Href =>
    asHref(`/(auth)/confirm-email?email=${encodeURIComponent(email)}`),
  tabs: asHref('/(tabs)'),
  /** Search screen, pushed from the Home header (hidden tab). */
  search: asHref('/(tabs)/search'),
  /** Title detail screen (hidden tab). */
  title: (id: string): Href => asHref(`/(tabs)/title/${id}`),
  /** Friends management (hidden tab), from Profile. */
  friends: asHref('/(tabs)/friends'),
  /** Deep-link invite accept route (outside tab bar). */
  inviteAccept: (code: string): Href => asHref(`/invite/${code}`),
  onboarding: {
    services: asHref('/(onboarding)/services'),
    tasteSeed: asHref('/(onboarding)/taste-seed'),
    handle: asHref('/(onboarding)/handle'),
    watchWith: asHref('/(onboarding)/watch-with'),
    invite: asHref('/(onboarding)/invite'),
    notifications: asHref('/(onboarding)/notifications'),
  },
} as const;
